version: "3.9"
services:
  web-db:
    platform: linux/x86_64
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: darkweb-db
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "15672:15672"

  tor-analyzer-worker:
    build:
      context: ./crawler
      dockerfile: Dockerfile.dev
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      PYTHONUNBUFFERED: 0
    depends_on:
      - rabbitmq
    volumes:
      - ./crawler/:/app/
    command:
      - bash
      - -c
      - |
        bash -c 'while !</dev/tcp/rabbitmq/5672; do echo "rbmq is not up. sleep 1 second..."; sleep 1; done;'
        python tor_analyzer_worker.py
        

  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile.dev
    environment:
      CLIENT_PORT: http://localhost:3000
      COOKIE_SECRET: cookiesecret
      JWT_SECRET_KEY: jwtsecretkey
      PORT: 3065
      MYSQL_DATABASE: darkweb-db
      MYSQL_HOST: web-db
      MYSQL_PASSWORD: mysql
      MYSQL_USERNAME: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      - web-db
      - rabbitmq
    ports:
      - "3065:3065"
    volumes:
      - ./web-server/:/app/
    command:
      - bash
      - -c
      - |
        bash -c 'while !</dev/tcp/web-db/3306; do echo "db is not up. sleep 1 second..."; sleep 1; done;'
        echo 'db is up! 10 seconds sleep more'
        sleep 20
        echo 'now run server'
        npm run dev

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_BACKEND_HOST: localhost
      REACT_APP_BACKEND_PORT: 3065
    ports:
      - "3000:3000"
    volumes:
      - ./web-client/:/app/
    command:
        - bash
        - -c
        - |
          npm run start